name: console_simple
description: A simple command-line application.
version: 1.0.0

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  args: ^2.0.0
  antlr4:
    path: ../../

dev_dependencies:
  pedantic: ^1.10.0
