name: Windows

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: [self-hosted, windows, x64]
    strategy:
      fail-fast: false
      matrix:
#       TARGET: [java, cpp, csharp, dart, go, javascript, php, python2, python3]
        TARGET: [java, python3]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.5.4    
    - name: Build tool with Maven
      run: mvn install -DskipTests=true -Darguments="-Dmaven.javadoc.skip=true" -B -V
    - name: Test with Maven
      run: .github/scripts-windows/run-tests-${{ matrix.TARGET }}.cmd
      env:
        TARGET: ${{ matrix.TARGET }}
